apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: pulse-sample-app
  namespace: pulse
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pulse-sample-app
  template:
    metadata:
      labels:
        app: pulse-sample-app
    spec:
      containers:
      - name: pulse-sample-app
        # 🌟 드디어 가짜 주소가 아닌, 방금 업로드한 진짜 대장님의 주소를 꽂아 넣습니다!
        image: yoon327/pulse-sample-app:v3 
        ports:
        - containerPort: 8080
  # -------------------------------------------------------------
  # [★핵심] 프로메테우스 자동 감시단이 결합된 카나리 전략
  # -------------------------------------------------------------
  strategy:
    canary:
      steps:
      - setWeight: 25
      # 25% 상태로 멈췄을 때, 어제 만든 자동 평가지(pulse-error-rate-check)를 가동합니다!
      - pause: {}
        analysis:
          templates:
          - templateName: pulse-error-rate-check
      - setWeight: 50
      - pause: {duration: 10s}
      - setWeight: 100
---
apiVersion: v1
kind: Service
metadata:
  name: pulse-sample-app-service
  namespace: pulse
spec:
  type: ClusterIP
  ports:
  - port: 8080       
    targetPort: 8080 
  selector:
    app: pulse-sample-app