apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: pulse-sample-app
  namespace: pulse              # 방 이름도 우리 앱이 사는 'pulse'로 지정!
spec:
  replicas: 4                    # 카나리 비율을 시각적으로 예쁘게 보려고 4대로 유지합니다.
  selector:
    matchLabels:
      app: pulse-sample-app
  template:
    metadata:
      labels:
        app: pulse-sample-app
    spec:
      containers:
      - name: pulse-sample-app
        image: yoonseo/pulse-sample-app:v1  # 🌟 안전한 구버전(v1) 이미지로 출발!
        ports:
        - containerPort: 8085               # 🌟 우리 Node.js 앱 포트인 8085로 매핑!
  # -------------------------------------------------------------
  # [★핵심] 카나리 배포 전략
  # -------------------------------------------------------------
  strategy:
    canary:
      steps:
      - setWeight: 25        # 1. 새 버전이 나오면 딱 25%만 먼저 보낸다 (4대 중 1대만 테스트)
      - pause: {}            # 2. 💡 [수정] 대기시간(1m) 대신 '무한 대기'로 바꿔서 안젤라님이 승인 버튼 누를 때까지 딱 멈춰 서게 만들게요! (손맛용)
      - setWeight: 50        # 3. 승인하면 50%까지 확대
      - pause: {duration: 10s} # 4. 10초 동안 간 보다가 문제없으면 100% 완전 교체!
---
apiVersion: v1
kind: Service
metadata:
  name: pulse-sample-app-service
  namespace: pulse
spec:
  type: ClusterIP
  ports:
  - port: 8085               # 밖에서 들어오는 포트
    targetPort: 8085         # 컨테이너 안으로 보내는 포트
  selector:
    app: pulse-sample-app