apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: pulse-sample-app
  namespace: pulse  # 🌟 아까 터미널로 만든 전용 방으로 입주!
spec:
  replicas: 1         # 안전한 슬롯 방어선
  selector:
    matchLabels:
      app: pulse-sample-app
  template:
    metadata:
      labels:
        app: pulse-sample-app
    spec:
      containers:
      - name: pulse-sample-app
        image: yoon327/pulse-sample-app:v3
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
  # -------------------------------------------------------------
  # 📊 [감시단 부활] 프로메테우스 안테나 연동 완료!
  # -------------------------------------------------------------
  strategy:
    canary:
      analysis:
        templates:
        - templateName: pulse-error-rate-check # 관제탑에 신호 쏠 분석기 이름
      steps:
      - setWeight: 25
      - pause: {} # 👈 첫 25% 트래픽 넘기고 대장님의 승인을 기다리는 정지선
      - setWeight: 50
      - pause: {duration: 10s}
      - setWeight: 100
---
apiVersion: v1
kind: Service
metadata:
  name: pulse-sample-app-service
  namespace: pulse
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: pulse-sample-app
